[versions]
agp = "8.13.1"
core = "1.7.0"
itext7Core = "7.2.5"
jfreechart = "1.5.6"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
loggingInterceptor = "5.3.0"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
mockitoInline = "5.2.0"
mpandroidchart = "v3.1.0"
retrofit = "3.0.0"
retrofitMock = "3.0.0"
robolectric = "4.16"
room = "2.8.3"
jetbrains-annotations = "26.0.2-1"
work = "2.11.0"
fuzzywuzzy = "1.4.0"
markwon = "4.6.2"
mockito = "5.20.0"
poi = "5.4.1"
secrets = "2.0.1"

[libraries]
core = { module = "androidx.test:core", version.ref = "core" }
itext7-core = { module = "com.itextpdf:itext7-core", version.ref = "itext7Core" }
jfreechart = { module = "org.jfree:jfreechart", version.ref = "jfreechart" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-mock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofitMock" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
work = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
fuzzywuzzy = { group = "me.xdrop", name = "fuzzywuzzy", version.ref = "fuzzywuzzy" }
markwon = { module = "io.noties.markwon:core", version.ref = "markwon" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
poi = { module = "org.apache.poi:poi", version.ref = "poi" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
work-testing = { module = "androidx.work:work-testing", version.ref = "work" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
